### PR TITLE
Update setup_walkoff.py to use python3

### PR DESCRIPTION
**Pull request by astrohart**
Per the new requirement to use Python 3 only

### CODE REVIEW

**Comment by iadgovuser11** [comment]
Could you make the edits off of the development branch instead of the master?  Thanks for the submission!

**Comment by adpham95** [comment]
Thanks for the pull request; this issue has been addressed in the development branch by using `sys.executable`: https://github.com/nsacyber/WALKOFF/blob/development/setup_walkoff.py 

This ensures the dependencies will be installed with the same python executable that invoked the setup script, without explicitly invoking `python3` as not all systems or users follow that convention. 

If you don't want to get the entire dev branch, you can grab that file individually by running in the repo's root directory:

`git checkout development -- requirements.txt && git checkout development -- setup_walkoff.py`

We haven't made a release to master yet as we're still going through a major refactor for a 1.0 release. 

The 1.0 release aims to be entirely containerized using Docker; among other benefits, it becomes the only requirement/dependency on the host system and provides a consistent/known Python environment for us in the containers.

**Comment by astrohart** [comment]
While, in principle, wanting to leave changes in the development branch is fine, however, I have a concern about rejecting this small point change.  In that, most new users/installers of WALKOFF are going to just be doing a dumb (not calling anyone stupid, just using a figure of speech)
```
$ git clone <git url from just googling the GitHub>
```
and/or downloading the ZIP.  The ```setup_walkoff.py``` that is currently in ```master``` already breaks ```master``` since ```master```, as currently cloneable, depends on Python 3.4+ only already. 

Why leaving ```setup_walkoff.py``` as is breaks ```master``` is that it does so on Ubuntu VMs.  As we all know, Ubuntu loves to ship (and depend on heavily) Python 2.7+.  When attempting to clone, install, and use WALKOFF just the other day, a colleague of mine were tripped up by this since it did not install with the ```setup_walkoff.py``` right out of the box.

One might raise the point, "Well, they can clone the ```development``` branch then."  However, for a new user fresh to WALKOFF, neither the github.io website nor the Overview video say this, they both have people cloning straight from ```master```, which does not work out of the box on Ubuntu.

So, I strongly urge you to re-evaluate rejecting this pull request.  My suggested course of action is to ensure that ```master``` is clonable and installable "out of the box."   There are, in my mind, two options for doing this:

- Adopt my submitted ```setup_walkoff.py``` as a "band-aid" fix; or
- Merge the ```setup_walkoff,py``` from the ```development``` branch right into the ```master``` branch.  

Option #2 is tantalizing, since it appears that the ```setup_walkoff.py``` from ```development``` could be easily merged into ```master``` as a standalone, so that then new users/installers do not have to waist their time going down a rabbit hole wondering how come they're following the docs and it's still not working.

Moreover, I think it's very bad practice to force new users to check out an ENTIRE branch, and an unstable (i.e., ```development```) and un-documented one, at that, just to get ONE file.

**Comment by astrohart** [comment]
See #214 and #212.

**Pull request closed without merging**
